name: CI MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "Project/wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup environment Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies menggunakan pip, sesuai dengan file conda.yaml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Menginstal library yang tercantum di conda.yaml
          pip install numpy pandas scikit-learn mlflow

      # 4. Menjalankan MLflow Project dengan parameter yang benar
      - name: Run mlflow project
        run: |
          mlflow run Project --env-manager=local \
            -P alpha=${{ env.ALPHA }} \
            -P l1_ratio=${{ env.L1_RATIO }} \
            -P csv_url=${{ env.CSV_URL }} \
            -P random_state=${{ env.RANDOM_STATE }}
