name: Test Workflow Trigger

on:
  push:
    branches:
      - main # atau master, sesuaikan dengan nama branch Anda

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Workflow berhasil terpicu!"
